--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Julicraft44/ShortCommands
build-by-default: true
branches:
- master
projects:
  ShortCommands:
    path: ""
    lint:
      phpstan: false
...
